numero_1=int(input("ingrese el primer numero: "))
numero_2=int(input("ingrese el segundo numero: "))
suma=(numero_1 + numero_2)
print(suma)
multiplicación=( numero_1 * numero_2)
print(multiplicación)
iguales=( numero_1 == numero_2)
print(iguales)
menor=( numero_1 < numero_2)
print(menor)
mayor=( numero_1 <= numero_2)
print(mayor)